### ISSUE TITLE
Feature: API General Task captures meta-data for args and arg sweeps

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-toshi-api#70]
We want to capture the job specs for the General Task, 

**so that** it's possible to validate and automate more features in nzshm-runzi

**Done when:**
 - [x] all arguments passed to the high_level runzi scripts (automation/run_*.py) are saved as meta data
 - [x] env/metrics can be used to capture job metadata (allowing replacement of https://docs.google.com/spreadsheets/d/153famuOt-dGSCdsdN8e2NZupxeuLWwHivPkL6-mgwi0)
 - [x] list the swept args/values

**Comment by chrisbc** [comment]
closed by #70
